"""add staff service assignments

Revision ID: 87964e32cdca
Revises: 049186910965
Create Date: 2026-09-18 16:03:42.026714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87964e32cdca'
down_revision: Union[str, Sequence[str], None] = '049186910965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_services',
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('staff_member_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_services')
    # ### end Alembic commands ###
