"""add staff assignment mode to services

Revision ID: 8a4c69627c6d
Revises: 87964e32cdca
Create Date: 2026-09-18 17:52:51.770091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4c69627c6d'
down_revision: Union[str, Sequence[str], None] = '87964e32cdca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'services',
        sa.Column(
            'staff_assignment_mode',
            sa.String(length=30),
            nullable=True,
        )
    )

    op.execute(
        "UPDATE services "
        "SET staff_assignment_mode = 'optional' "
        "WHERE staff_assignment_mode IS NULL"
    )

    op.alter_column(
        'services',
        'staff_assignment_mode',
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'staff_assignment_mode')
    # ### end Alembic commands ###
